#ifndef LCD_CONFIG_H
#define LCD_CONFIG_H

#define EXAMPLE_LCD_H_RES              360
#define EXAMPLE_LCD_V_RES              360

#define LCD_BIT_PER_PIXEL              16

// JC3636K718C (ST77916) QSPI pins
#define EXAMPLE_PIN_NUM_LCD_CS      12
#define EXAMPLE_PIN_NUM_LCD_PCLK    11
#define EXAMPLE_PIN_NUM_LCD_DATA0   13
#define EXAMPLE_PIN_NUM_LCD_DATA1   14
#define EXAMPLE_PIN_NUM_LCD_DATA2   15
#define EXAMPLE_PIN_NUM_LCD_DATA3   16
#define EXAMPLE_PIN_NUM_LCD_RST     17
#define EXAMPLE_PIN_NUM_BK_LIGHT    21

#define EXAMPLE_LVGL_BUF_HEIGHT        (EXAMPLE_LCD_V_RES / 10)
#define EXAMPLE_LVGL_TICK_PERIOD_MS    2
#define EXAMPLE_LVGL_TASK_MAX_DELAY_MS 500
#define EXAMPLE_LVGL_TASK_MIN_DELAY_MS 1
#define EXAMPLE_LVGL_TASK_STACK_SIZE   (4 * 1024)
#define EXAMPLE_LVGL_TASK_PRIORITY     2

// JC3636K718C touch (CST816S) pins
#define EXAMPLE_TOUCH_ADDR            0x15
#define EXAMPLE_PIN_NUM_TOUCH_SCL     10
#define EXAMPLE_PIN_NUM_TOUCH_SDA     9
#define EXAMPLE_PIN_NUM_TOUCH_INT     7
#define EXAMPLE_PIN_NUM_TOUCH_RST     8

#endif